dist: trusty
sudo: false

language: scala

jdk:
  - oraclejdk8
  - openjdk11

scala:
  - 2.12.8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "axiw4x8VWpruLeH2F9Mag4gsqpcFUQ44L3V0468SMZzf5B8rQdCrXtouW1OLYwgQeQOn3mM3qjNa2cTehBwXtXpn5Ir1xk2kJtpIzdEoddXTd0oPmaP45pES9vJGIgKTUiaXTKcDZMo7L3D1rJb6mWmx2EQbSqE50NlCNGsYn/TftYVWNCsICAZHoWe6F3pDEcdtzfwLsNzbxxDTTfMQjZg6fX+eYy71L5z+lyMlaQ9H+hFdX+6IToeGb41qWb48hnfRwnv/1pO3JzSPYfo+62vYJMM6/e/zVH2DToXsod0g4NSfXelZO7EXQdhMJBNCIRLSPPQRqDY+iHtvsOSWRmU7cAmic0ze/n8FM+3Z6fIL2Rsg3xyGK2lUfL3ifZhUZT/NVeavPWAtYB1F1hv9D1/yrj7cDZExdmTl8C6gU8EmWqD6/rBN+9TbeyRtqEWE66gGBGV1ROej+9v7iJKyQ8lG5h3jt19j/EZG3mJFraXYh7cANZJ0AahC8b6miuKWRRzCqdMSIV3gRwAk1BrHNu0k+aPmn//VHOwL91jNPWtwKf/a01q/o22M5hZjmAPDIttC7iV4MgbBjakthAD7rcOhsH4TMSLZpzM5fSQQ6eTbM+y1Zwokmn1xyT7rrVhG0sa2djy2c53wiyHTbeKPjihrJ5ExzazJhN6f9RRYDsQ="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete